language: python
python:
- '3.5'
script:
- flake8 .
- bandit -r .
deploy:
  provider: pypi
  user: briggsb
  password:
    secure: Pgn00ivswNNYFkr3Laq+oFTKTtjWnoFOnHoelOu9Jv+qHgYuoedxMPi9TCmQYVzvgF9485sPrM5NclkxgjfzA3w2nh2LHcDubwNDouRerP3yxKjCxWPRAt4ADzYxggC0pFlolGEsUiaKaq+kSnv+vvqQ8yL5XiS7Q9bw+cMMzTmZDXLNe0WH+DYQX6sXgSSXMVYayMH3aMryuPvlwwEmGPqnVzdMB7wAFMkMS1IDf+3plWltZxAFANqnJTaFJrXX3fMJu90LGTJpCBtTwWKoGHQwBs9rp9PNqn7t+t3pwKRlX2I9fTPCgiNHyllCPJVlgpzqq4mNSMnkTcVbCE+U75zUlSSl4/gIE73zQIhDFscPxwJONJ0XhLu2EE0g1l1ut1/jrD0uROgoxYdjh8CPxB+TCjcM6sZbzunqh4QO2UADBg2rzTM5skJrlvUhnb0f74YiWa7CjcwaQ36PR4UP1jjPL5Cb6LpgOBr98F5Kx9wDXGwQGUUCUziGlzKKiA1wRNtKQjdJiCkIIVaARN8h5wGgIVqdKH6zsU6amX6CZOG8r5m+tgLC+wGf+7upzi7FCyDpB8iFomdTYC4162sujq+/bhHjFlfgWFVNBFpBVO5jqw73+ctS+2uGx5zyqX7VFO/9t9mcJ8S05/ddSi+DrgINhsLpigHTmyi+5qSjl0k=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bbriggs/legos.stocks
